"""adds description to links

Revision ID: 58a649225fbb
Revises: 447ff69d884a
Create Date: 2021-05-02 12:50:11.299650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a649225fbb'
down_revision = '447ff69d884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'description')
    # ### end Alembic commands ###
