"""Adds order column to collections

Revision ID: 63616e5cabb3
Revises: 5a5a5b6ff952
Create Date: 2021-05-24 11:00:41.194613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63616e5cabb3"
down_revision = "5a5a5b6ff952"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "order")
    # ### end Alembic commands ###
