"""Added email and firebase UID columns to User

Revision ID: 9ae56a4d7911
Revises: f1b4d6270d43
Create Date: 2021-01-31 13:39:45.500137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ae56a4d7911"
down_revision = "f1b4d6270d43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "user", sa.Column("external_uid", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "external_uid")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
