# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run application tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    name: Run all tests with pytest
    runs-on: ubuntu-latest
    env:
        DB_PASSWORD: supersecure
        DB_USER: tester
        DB_DATABASE: sunset_test
        FIREBASE_ENABLED: 0
        TESTING: 1

    steps:
    - uses: actions/checkout@v2
    - name: Start up test database 
      run: docker-compose up -d db 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
    - name: Test with pytest
      run: pipenv run pytest -v
    